<?php
session_start();

if (!isset($_SESSION['email']) || $_SESSION['role'] == 1) { 
    header("location: LogIn.php");
    exit();
}

?>

<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link type="text/css" href="styles/JobListingStyles.css" rel="stylesheet" />
    <link type="text/css" href="styles/postEditJob.css" rel="stylesheet" />
    <link rel="stylesheet" href="styles/Buttons.css" />
    <link type="text/css" href="styles/NavbarStyles.css" rel="stylesheet" />
    <link rel="stylesheet" href="styles/Notifications.css" />
    <link type="text/css" href="styles/Footer.css" rel="stylesheet" />
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <link rel="icon" href="img/icon.png" />
    <title>Employer | Edit A Job</title>
  </head>

  <body>
    <?php
    $jobId=$_GET['ID'];

    if (!($database = mysqli_connect("localhost", "root", "")))
        die("<p>Could not connect to database</p>");

    if (!mysqli_select_db($database, "jobhunter"))
        die("<p>Could not open URL database</p>");

    
    $query = "select * from job WHERE ID='$jobId'";
    $result = mysqli_query($database, $query);

    if ($result) {
      while ($data = mysqli_fetch_assoc($result)) {
      //$jobTitle=$data[];
      $major=$data [`major`];
      $position=$data [`position`];
      $jobDescription=$data [`description`];
      $requiredSkills=$data [`skills`];
      $requiredQ=$data [`qualifications`];
      $location=$data [`city`];
      $jobType=$data [`jobType`];
      $gender=$data [`gender`];
      $salaryInput=$data [`salary`];

    }
    }
    
    ?>
    <!-- popup for notifications -->
    <div class="popup" id="popup">
      <div class="popup-inner">
        <a href="#" id="closeIcon" class="closeIcon"
          ><i class="material-icons">close</i></a
        >
        <div class="notificationList">
          <ul>
            <li class="notificationRow">
              <div class="notificationIcon">
                <i class="material-icons">notifications_active</i>
              </div>
              <div class="content">
                <h3>
                  Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                </h3>
                <p class="date">February 11th 2021</p>
              </div>
            </li>
            <li class="notificationRow">
              <div class="notificationIcon">
                <i class="material-icons">notifications_active</i>
              </div>
              <div class="content">
                <h3>
                  Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                </h3>
                <p class="date">February 11th 2021</p>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <!-- header and logo -->
    <span class="logo"><img src="img/logo.PNG" alt="logo" /></span>
    <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->
    <div style="height: 150px; overflow: hidden">
      <svg
        viewBox="0 0 500 150"
        preserveAspectRatio="none"
        style="height: 100%; width: 100%"
      >
        <path
          d="M-15.58,-15.49 C-16.70,110.81 186.45,57.52 502.48,59.50 L500.00,0.00 L0.00,0.00 Z"
          style="stroke: none; fill: #8cb3f4"
        ></path>
      </svg>
    </div>
    <header>
      <nav>
        <ul class="navLinks1">
          <li><a href="home.php">Home</a></li>
          <li><a href="jobSeekerSearch.html">Job Seekers</a></li>
          <li>
            <a href="#">My Jobs</a>
            <ul>
              <li><a href="JobListing.html">All Jobs</a></li>
              <li><a href="PostAJob.php">Post a Job</a></li>
            </ul>
          </li>

          <li><a href="myAdvices.html"> My Advices </a></li>
        </ul>
        <ul class="navLinks2">
          <li>
            <a href="#popup" class="notification"
              ><i class="material-icons">notifications</i></a
            >
          </li>
          <li>
            <a href="#"><i class="material-icons">person</i></a>
            <ul>
              <li><a href="EmployerProfile.html">Profile</a></li>
              <li><a href="home.php">Log out</a></li>
            </ul>
          </li>
        </ul>
      </nav>
    </header>

    <form action="EditAJob.php" method="POST">
      <fieldset>
        <legend class="postLegend">Edit A Job</legend>
<!-- 
        <div class="inputDiv">
          <label class="theTitle" for="jobTitle"> Job Title </label>
          <input id="jobTitle" type="text" value="<?php echo ;?>" />
        </div> -->
        <div class="inputDiv">
          <label for="position">Job Position</label>
          <input id="position" type="text" value="<?php echo $position;?>" />
        </div>

        <div class="inputDiv">
          <label for="major"> Major </label>
          <select id="major">
            <script>
              $("#major").val("<?php echo $major?>");
            </script>
            <option value="Select a major" selected>Select a major</option>
            <option value="Accounting & Finance">Accounting & Finance</option>
            <option value="Agriculture & Forestry">Agriculture & Forestry</option>
            <option value="Archaeology">Archaeology</option>
            <option value="Architecture">Architecture</option>
            <option value="Art">Art</option>
            <option value="Biological Sciences">Biological Sciences</option>
            <option value="Business & Management">Business & Management</option>
            <option value="Chemical Engineering">Chemical Engineering</option>
            <option value="Chemistry">Chemistry</option>
            <option value="Civil Engineering">Civil Engineering</option>
            <option value="Communication & Media Studies">Communication & Media Studies</option>
            <option value="Computer Science">Computer Science</option>
            <option value="Economics & Econometrics">Economics & Econometrics</option>
            <option value="Education">Education</option>
            <option value="Electrical & Electronic Engineering">Electrical & Electronic Engineering</option>
            <option value="General Engineering">General Engineering</option>
            <option value="Geography">Geography</option>
            <option value="Geology, Environmental, Earth & Marine Sciences">Geology, Environmental, Earth & Marine Sciences</option>
            <option value="Law">Law</option>
            <option value="Mathematics & Statistics">Mathematics & Statistics</option>
            <option value="Mechanical & Aerospace Engineering">Mechanical & Aerospace Engineering</option>
            <option value="Medicine & Dentistry">Medicine & Dentistry</option>
            <option value="Other">Other</option>
          </select>
          <!--https://stackoverflow.com/questions/8763869/append-input-text-field-with-value-of-a-div  -->
          <script>
            if( $("#major").val()==="Other"){
              $("#major").append(
                $('<input>', {
                  type: 'text',
                  val:  <?php echo $major;?>
                 }
                )
              )
            }
          </script>

        </div>



      
      
      
      

        <div class="inputDiv">
          <label for="jobDescription"> Job Description</label>
          <textarea id="jobDescription" style="resize: none"><?php echo $jobDescription;?></textarea>
        </div>

        <div class="inputDiv">
          <label for="requiredSkills"> Required Skills</label>
          <textarea id="requiredSkills" style="resize: none"><?php echo $requiredSkills;?></textarea>
        </div>

        <div class="inputDiv">
          <label for="requiredQ"> Rrequired Qualifications</label>
          <textarea id="requiredQ" style="resize: none"><?php echo $requiredQ;?></textarea>
        </div>

        <div class="inputDiv">
          <label for="location"> Location</label>
          <input id="location" type="text" value=<?php echo $location;?> />
        </div>

        <fieldset>
          <legend class="notFormHeader">Job Type</legend>
          <script>
            if(<?php echo $jobType;?> ==="FullTime"){
              $('#FullTime').attr('checked', 'checked');
            }
            else{
              $('#partTime').attr('checked', 'checked');
            }
            
          </script>
          <label class="rLabel">
            <input type="radio" name="jobType" id="FullTime" value="FullTime" />
            Full-time
          </label>

          <label class="rLabel">
            <input type="radio" name="jobType" id="partTime"  value="partTime" />
            Part-time
          </label>
        </fieldset>

        <fieldset>
        <legend>Gender</legend>
        <script>
            if(<?php echo $gender;?> ==="Female"){
              $('#Female').attr('checked', 'checked');
            }
            else{
              $('#Male').attr('checked', 'checked');
            }
            
          </script>
<label class="rLabel">
  <input type="radio" name="gender" value="Female" id="Female" checked="checked" />
  Female
</label>

<label class="rLabel" id="Male">
  <input type="radio" name="gender" id="Male" value="Male"/>
  Male
</label>
        </fieldset>

        <div class="inputDiv">
          <label for="salaryInput" id="SalaryL"> Salary Starts From </label>
          <input type="number" min="0" id="salaryInput" value=<?php echo $salaryInput;?> />
          <!--https://stackoverflow.com/questions/7372067/is-there-any-way-to-prevent-input-type-number-getting-negative-values -->
        </div>

        <a href="/JobListing.html" style="text-decoration: none"
          ><input type="button" value="Delete"
        /></a>
        <a href="/JobListing.html"><input type="submit" value="Save" /></a>
      </fieldset>
    </form>

    <!-- Footer -->
    <div class="footer">
      <div class="footer-content">
        <p>Contact us</p>
        <span class="material-icons">facebook</span>
        <a href="mailto:jobhunter@ksu.com"
          ><span class="material-icons">email</span></a
        >
      </div>
      <div class="shape-footer" style="height: 150px; overflow: hidden">
        <svg
          viewBox="0 0 500 150"
          preserveAspectRatio="none"
          style="height: 100%; width: 100%"
        >
          <path
            d="M-15.58,-15.49 C-16.70,110.81 186.45,57.52 502.48,59.50 L500.00,0.00 L0.00,0.00 Z"
            style="stroke: none; fill: #8cb3f4"
          ></path>
        </svg>
      </div>
    </div>
  </body>
</html>
