<!DOCTYPE html>

<html>

<head>
    <meta charset="UTF-8" />
    <title>Employer Registration</title>
    <link rel="stylesheet" href="styles\JobListingStylesFay.css" />
    <link rel="icon" href="img/icon.png">
    <link rel="stylesheet" href="styles\Buttons.css" />
    <link rel="stylesheet" href="styles\NavbarStyles.css" />
    <link rel="stylesheet" href="styles\form.css" />
</head>

<body>
    <?php
        if (!( $database = mysqli_connect( "localhost", "root", "" )))
            die( "<p>Could not connect to database</p>" );

        if (!mysqli_select_db( $database, "JobHunter" ))
            die( "<p>Could not open URL database</p>" );

        if(isset($_POST['create'])){
            $name = $_POST['name'];
            $scope = $_POST['scope'];
            $phone = $_POST['phone'];
            $password = $_POST['password'];
            $re_pass = $_POST['re_password'];
            $email = $_POST['email'];
            $address = $_POST['address'];
            $des = $_POST['des'];
            $mission = $_POST['mission'];
            $vision = $_POST['vision'];

            $test = "INSERT INTO employer(name, scope, phone, password, email, address, des, mission, vision) VALUES('".$name."', '".$scope."', '".$phone."', '".$password."', '".$email."', '".$address."', '".$des."', '".$mission."', '".$vision."');";
            $res=mysqli_query($database,$test);
            if($res)
                header("Location: home.html");
        }
    ?>
    <span class="logo"><img src="img/logo.PNG" alt="logo"></span>
    <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->
    <div style="height: 150px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none"
            style="height: 100%; width: 100%;">
            <path d="M-15.58,-15.49 C-16.70,110.81 186.45,57.52 502.48,59.50 L500.00,0.00 L0.00,0.00 Z"
                style="stroke: none; fill: #8CB3F4;"></path>
        </svg></div>
    <header>
        <nav>
            <ul class="navLinks1">
                <li><a href="home.html">Home</a></li>
                <li><a href="jobSearch.html">Jobs</a></li>
                <li><a href="LogIn.html">Login</a></li>
            </ul>
        </nav>
    </header>

    <main>
        <section class="background">
            <div class="lists">
                <div class="list">
                    <img class="regimg" src="img/6671.jpg" alt="v">
                    <div class="jobInfo">
                        <h2 id=employerReg>Employer Regstration </h2>
                        <form method="post" action="EmployeerReg.php">
                            <label for="first_name">Company's name</label>
                            <input type="text" class="form-input" name="name" id="fCOMPANY'S NAME" placeholder="Company's name.. " required />
                            <label for="first_name">Company's scope</label>
                            <input type="text" class="form-input" name="scope" id="fCOMPANY'S NAME" placeholder="Company's name.. " required />
                            <label for="phone">Phone number</label>
                            <input type="text" class="form-input" name="phone" id="phone"
                                placeholder="Your phone number" required />
                            <label for="password">Password</label>
                            <input type="password" class="form-input" name="password" id="password"
                                placeholder="Your password" required />
                            <label for="re_password">Repeat your password</label>
                            <input type="password" class="form-input" name="re_password" id="re_password"
                                placeholder="Repeat your password" required />
                            <label for="last_name">Email</label>
                            <input type="email" class="form-input" name="email" id="last_name"
                                placeholder="Your email..." required />
                            <label for="last_name">Address</label>
                            <input type="text" class="form-input" name="address" id="last_name"
                                placeholder="Your headquarter's address" required />
                            <label for="last_name">Description of Company</label>
                            <textarea  style="resize: none; " rows="4" cols="53" placeholder="Enter a brief description.." name="des"></textarea>
                            <label for="last_name">Mission</label>
                            <input type="text" class="form-input" name="mission" id="last_name"
                                placeholder="List your company's mission.." required />
                            <label for="last_name">Vision</label>
                            <input type="text" class="form-input" name="vision" id="last_name"
                                placeholder="List your company's vision.." required />
                            <input type="submit" class="applicants" name="create">
                        </form>
                        <!-- <div class="buttons">
                            <a href="LastEMPProf.2html.html">
                                <button class="applicants">Sign Up</button>
                            </a>
                        </div> -->
                    </div>
                </div>
            </div>
        </section>
    </main>
</body>

</html>