<?php
session_start();
if (isset($_SESSION['email'])) {

    if ($_SESSION['role'] == 1)
        header("Location:JobSeekerViewProf.php");

    if ($_SESSION['role'] == 2)
        header("Location: EmployerProfile.php");
}

?>

<!DOCTYPE html>
<html>
<?php
if (!($database = mysqli_connect("localhost", "root", "")))
    die("<p>Could not connect to database</p>");

if (!mysqli_select_db($database, "jobhunter"))
    die("<p>Could not open URL database</p>");

if (isset($_POST['login'])) {
    $tybe = $_POST['tybeuser'];
    $email = $_POST['email'];
    $password = $_POST['password'];
    if (empty($_POST['email']) || empty($_POST['password'])) {
        header("Location: login.php?error=email and password are required");
        exit();
    }

    $query;
    if ($tybe == 2)
        $query = "select * from employer WHERE email='$email'AND password='$password'";
    else if ($tybe == 1)
        $query = "select * from jobseeker WHERE email='$email'AND password='$password'";

    $run = mysqli_query($database, $query);

    $numm = mysqli_num_rows($run);
    if ($numm > 0) {
        $_SESSION['email'] = $email;
        $_SESSION['value'] = $tybe;

        if ($tybe == 1) {
            $_SESSION['role'] = 1;
            header("Location:JobSeekerViewProf.php");
        }
        if ($tybe == 2) {
            $_SESSION['role'] = 2;
            header("Location: EmployerProfile.php");
        }
    } else {
        header("Location: logIn.php?error=Wrong Username/Password");
        exit();
    }
}
?>
<head>
    <meta charset="UTF-8" />
    <title>Log in</title>
    <link rel="stylesheet" href="styles\JobListingStylesFay.css" />
    <link rel="icon" href="img/icon.png">
    <link rel="stylesheet" href="styles\Buttons.css" />
    <link rel="stylesheet" href="styles\NavbarStyles.css" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="styles\form.css?<?php echo time(); ?>" />
    <style>

        .custom-shape-divider-bottom-1612535207 {
            position: absolute;
            left: 0;
            width: 100%;
            overflow: hidden;
            line-height: 0;
            transform: rotate(180deg);
        }


        .custom-shape-divider-bottom-1612535207 svg {
            position: relative;
            display: block;
            width: calc(222% + 1.3px);
            height: 218px;
            transform: rotateY(180deg);
        }

        .custom-shape-divider-bottom-1612535207 .shape-fill {
            fill: #8cb3f4;
        }

        .footer-content {
            position: absolute;
            padding-left: 100px;
            padding-top: 100px;
        }

        .footer {
            display: inline-block;
        }

        .company-icon {
            fill: #2b468b;
            margin-top: 10px;
            margin-left: -190px;
        }

        .company {
            text-align: left;
            padding-top: 8px;
            padding-left: 10px;
        }

        .shape-footer {
            transform: rotateX(180deg);
            width: 100%;
            position: absolute;
        }



        .footer-content {
            position: absolute;
            z-index: 3;
            font-family: "Lucida Sans", "Lucida Sans Regular", "Lucida Grande",
                "Lucida Sans Unicode", Geneva, Verdana, sans-serif;
            font-size: 16px;
            color: #192d50;
            /* margin-top: 5px; */
            margin-left: 35%;
            display: inline-flex;
        }

        .footer-content span {
            padding-left: 10px;
            text-decoration: none;
            color: #192d50;
        }

        .footer-content span:hover {
            color: rgba(234, 243, 250, 0.8);
            transform: scale(1.1);
            transition: 0.3s ease-in;
        }

        #page-container {
            position: relative;
            min-height: 120vh;
        }

        #content-wrap {
            padding-bottom: 2.5rem;
            /* Footer height */
        }

        #footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            height: 2.5rem;
            /* Footer height */
        }
    </style>
</head>



<body>
    <div id="page-container">
        <div id="content-wrap">
            <!-- all other page content -->
            <span class="logo"><img src="img/logo.png" alt="logo"></span>
    <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->
    <div style="height: 150px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;">
            <path d="M-15.58,-15.49 C-16.70,110.81 186.45,57.52 502.48,59.50 L500.00,0.00 L0.00,0.00 Z" style="stroke: none; fill: #8CB3F4;"></path>
        </svg></div>
    <header>
        <nav>
            <ul class="navLinks1">
                <li><a href="home.php">Home</a></li>
                <li><a href="jobSearch.php">Job</a></li>
                <li><a href="EmployerSearch.php">Employers</a>

                </li>
            </ul>
    </header>
    <main>
        <br><br><br>
        <section class="background">
            <div class="lists">
                <div class="list">
                    <div class="jobInfo">
                        <br> <br>
                        <img class="regimg" src="img/undraw_Login_re_4vu2.png" alt="v">
                        <h2 id="employerReg">Log in </h2> <br>
                        <div id="f-div">
                            <form action="logIn.php" method="POST">
                                <?php
                                if (isset($_GET['error']))
                                    echo "<div class='alert' role='alert'>" . $_GET['error'] . "</div>";
                                ?>
                                <label for="">How are you?</label> <select name="tybeuser" id="rolew">
                                    <option value="2" selected>employer</option>
                                    <option value="1">job seeker</option>
                                </select> <br> <br>
                                <label for="first_name">Email</label>
                                <input type="email" class="form-input" name="email" id="first_name" placeholder="Your email.. " required autofocus /><br> <br>
                                <label for="password">Password</label>
                                <input type="password" class="form-input" name="password" id="password" placeholder="Your password"  required /> <br> <br>
                                <h4>Don't have an account yet? <a href="WhoAreYou.html">Sign Up </a> </h4>
                                <br>
                                <button name="login" type="submit" class="applicants">Log in</button>
                            </form>
                            
                        </div>
                    </div>
                </div>
            </div>
            <br> <br>
        </section>
    </main>
        </div>
        <footer id="footer">
                    <!-- Footer -->
        <div class="footer">
            <div class="footer-content">
                <p>Contact us</p>
                <span class="material-icons">facebook</span>
                <a href="mailto:jobhunter@ksu.com"><span class="material-icons">email</span></a>
            </div>
            <div class="shape-footer" style="height: 150px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;">
                    <path d="M-15.58,-15.49 C-16.70,110.81 186.45,57.52 502.48,59.50 L500.00,0.00 L0.00,0.00 Z" style="stroke: none; fill: #8CB3F4;"></path>
                </svg></div>
        </div>
        </footer>
    </div>
</body>

</html>

