<?php
session_start();

if (!isset($_SESSION['email']) ){
    header("location: LogIn.php");
    exit();
}

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="styles/selectstyle.css" />
    <link rel="stylesheet" href="styles/NavbarStyles.css" />
    
  <script>
      body{
        background-color: #FA9746;
      }
  </script>
</head>
<body>
<span class="logo"><img src="img/logo.PNG" alt="logo"></span>
    <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->
    <div style="height: 150px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none"
            style="height: 100%; width: 100%;">
            <path d="M-15.58,-15.49 C-16.70,110.81 186.45,57.52 502.48,59.50 L500.00,0.00 L0.00,0.00 Z"
                style="stroke: none; fill: #8CB3F4;"></path>
        </svg></div>
        <main>
        <div class="list">
                <div>
                    <img src="img/company.svg" alt="company default logo" class="defaultCompany" />
                </div>
                
                <!-- job description -->
                <a href="EmployerProf_edit.html">
                <div class="jobInfo">
                    <h2>Hiring Role</h2>
                    <span>
                        <svg class="locationIcon" xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24"
                            height="24" viewBox="0 0 24 24" width="24">
                            <g>
                                <rect fill="none" height="24" width="24" />
                            </g>
                            <g>
                                <path
                                    d="M12,2c-4.2,0-8,3.22-8,8.2c0,3.18,2.45,6.92,7.34,11.23c0.38,0.33,0.95,0.33,1.33,0C17.55,17.12,20,13.38,20,10.2 C20,5.22,16.2,2,12,2z M12,12c-1.1,0-2-0.9-2-2c0-1.1,0.9-2,2-2c1.1,0,2,0.9,2,2C14,11.1,13.1,12,12,12z" />
                            </g>
                        </svg>
                    </span>
                    <h6 class="location">City, Country</h6>
                    <span>
                        <svg class="majorIcon" xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24"
                            height="24" viewBox="0 0 24 24" width="24">
                            <g>
                                <path d="M0,0h24v24H0V0z" fill="none" />
                            </g>
                            <g>
                                <path
                                    d="M4,4v16c0,1.1,0.9,2,2,2h12c1.1,0,2-0.9,2-2V4c0-1.1-0.9-2-2-2H6C4.9,2,4,2.9,4,4z M11,4h5v6.12 c0,0.39-0.42,0.63-0.76,0.43L13.5,9.5l-1.74,1.05c-0.33,0.2-0.76-0.04-0.76-0.43V4z" />
                            </g>
                        </svg>
                    </span>
                    <h6 class="major">Required Major, Degree</h6>
                    <p class="jobDescription">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam veritatis saepe
                        cupiditate sequi beatae voluptate accusamus at. Pariatur, aperiam quaerat.
                    </p>
                    <h5>Starting salary <span class="salary"> $</span></h5>
                    <span class="workIcon"> <svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24"
                            viewBox="0 0 24 24" fill="black" width="24px" height="24px">
                            <g>
                                <g>
                                    <rect fill="none" height="24" width="24" y="0" />
                                </g>
                            </g>
                            <g>
                                <g>
                                    <path
                                        d="M20,6h-4V4c0-1.11-0.89-2-2-2h-4C8.89,2,8,2.89,8,4v2H4C2.89,6,2.01,6.89,2.01,8L2,19c0,1.11,0.89,2,2,2h16 c1.11,0,2-0.89,2-2V8C22,6.89,21.11,6,20,6z M14,6h-4V4h4V6z" />
                                </g>
                            </g>
                        </svg></span>
                    <h6 class="work">Part-time/Full-time</h6>
                </div> 
                
                
            
        
        
        </main> 
           
     
            <div id="myModal" class="modal">
     <!-- header and logo -->
    
                <!-- Modal content -->
                <div class="modal-content">
                    <div class="lineapp"></div>
                 <a href="Myapplicationlist.php"> <span class="close">&times;</span></a>
                  
                        <div id="head">   Select Appointment    </div>
                        
                      
              <?php 
              if(isset($_POST['selectapp'])){
                $id=$_POST['applayID'];
              if (!($database = mysqli_connect("localhost", "root", "")))
              die("<p>Could not connect to database</p>");
          
          if (!mysqli_select_db($database, "jobhunter"))
              die("<p>Could not open URL database</p>");
          $email = $_SESSION['email'];
              $query = "SELECT * FROM appointment,jobseeker_apply_job WHERE applay_JID=applay_ID AND applay_ID='$id'";
                       
              $result = mysqli_query($database, $query);
              
               if ($result) {
                 
                      while ($data= mysqli_fetch_assoc($result)) {
                        $Date0 = $data['date'];
                        $date = date("d-m-Y", strtotime($Date0));
                       $time = $data['time']; 
                       $idappo=$data['appointment_ID'];
                       $t;
                      $cheak=  substr($time,0,2);
                      if ($cheak>=12)
                      $t=" PM";
                      else
                      $t=" AM";

                      $time=$time.$t;
                       
                       
                      
                       ?>  
                        
                            
                              
                        <form action="popselect.php" method="POST" class="selectapy">
                            <input type="hidden" name="id" value="<?php echo $idappo ?>">
                           <button class="box"  name="selecteda"> 
                                <div id="date">Availabale appointment</div>
                                <div id="title"><h4> <?php echo $date;?></h4> <h4> <?php echo $time;?></h4></div>
                                 <div id="book"><h4> Book</h4></div> </button>  </form>
                               
                                 
                        
                           
                               
               
                  
                                   
                      
                              
                               
                                 <?php }} } else echo " ";?>                                                                                             
                 
                      </div>
                  </div> 
              
</body>  
<?php
$x=0;
 if(isset($_POST['selecteda'])){
    $idapoo=$_POST['id'];
    if (!($database = mysqli_connect("localhost", "root", "")))
    die("<p>Could not connect to database</p>");

if (!mysqli_select_db($database, "jobhunter"))
    die("<p>Could not open URL database</p>");
    
    $query="UPDATE appointment SET statuss=2  WHERE appointment_ID ='$idapoo'";              
    $result = mysqli_query($database, $query);
    
     if ($result) {
   
    
    print( "<script>x=alert('Thanks, your appointiment is confirmed');
    window.location.href = 'Myapplicationlist.php';
                                                     </script>");
    
} }  

?>




</html>